language: scala

jdk:
  - oraclejdk7
  - oraclejdk8

scala:
   - 2.11.12
   - 2.12.4
   - 2.13.0-M2

matrix:
  exclude:
  # We build Scala 2.11 on Java 7, so let's not bother with Java 8
  - jdk: oraclejdk8
    scala: 2.11.12
  # Scala 2.12+ requires Java 8
  - jdk: oraclejdk7
    scala: 2.12.4
  - jdk: oraclejdk7
    scala: 2.13.0-M2

before_install:
  - |
    git clone https://github.com/hashicorp/nomad-java-sdk
    cd nomad-java-sdk
    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    cd -

before_script:
  - |
    set -euo pipefail
    if [[ ! -f cache/bin/nomad ]]; then
      export GOPATH="$PWD/gopath"
      eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.9.2 bash)"
      export PATH="$PATH:$GOPATH/bin"
      go get -u github.com/hashicorp/nomad
      cd "$GOPATH/src/github.com/hashicorp/nomad"
      make bootstrap generate
      cd -

      mkdir -p cache/bin
      cd cache/bin
      go build -tags nomad_test github.com/hashicorp/nomad
      cd -
    fi
    set +euo pipefail  # restory options to work around https://github.com/travis-ci/travis-ci/issues/5434
  - export PATH="$PWD/cache/bin:$PATH"

script: sbt ++$TRAVIS_SCALA_VERSION scalastyle test

cache:
  directories:
    - $HOME/.m2
    - cache
